# html_tools.py
"""
HTML extraction utilities for remittance email bodies.

Real Adani emails are HTML with embedded tables. The body is generated by
Outlook/Word and is typical Microsoft HTML — heavy with style attributes,
nested spans, soft hyphens, and non-breaking spaces.

These tools handle the parsing so the agent can reason about table content
instead of HTML structure.
"""

import re
from typing import Any

from bs4 import BeautifulSoup, Tag


def extract_plain_text(html: str) -> str:
    """Strip HTML to plain text. Good for previewing or for LLM context."""
    soup = BeautifulSoup(html, "lxml")
    # Remove style and script
    for el in soup(["style", "script"]):
        el.decompose()
    text = soup.get_text(separator=" ", strip=True)
    # Normalize whitespace (Outlook HTML has lots of repeated spaces and nbsp)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def _normalize_cell(cell_text: str) -> str:
    """Clean a single cell value: strip whitespace, collapse spaces, handle dashes."""
    s = cell_text.strip()
    s = re.sub(r"\s+", " ", s)
    # Outlook puts non-breaking spaces and soft hyphens everywhere
    s = s.replace("\u00a0", " ").replace("\u00ad", "")
    # Dash-only cells often mean "0" or "—" in financial tables
    if s in {"-", "—", "–"}:
        return ""
    return s.strip()


def extract_html_tables(html: str) -> list[dict[str, Any]]:
    """Extract all <table> elements from HTML, return as list of structured dicts.

    Each table is returned as:
        {
            "rows": [[cell1, cell2, ...], [cell1, cell2, ...], ...],
            "row_count": int,
            "col_count": int,
            "header_row": [...] | None,   # heuristic: first row if it looks like headers
            "data_rows": [[...], ...],     # rows after the header
        }

    Header detection is heuristic: if the first row's cells contain mostly
    non-numeric content AND the second row's cells contain numeric content,
    treat the first row as headers. Otherwise no header is identified and
    all rows are data.
    """
    soup = BeautifulSoup(html, "lxml")
    tables = []
    for tbl in soup.find_all("table"):
        rows = []
        for tr in tbl.find_all("tr"):
            cells = [_normalize_cell(td.get_text(separator=" ", strip=True))
                     for td in tr.find_all(["td", "th"])]
            if cells:  # skip rows with no cells (formatting artifacts)
                rows.append(cells)

        if not rows:
            continue

        # Heuristic header detection
        header_row = None
        data_rows = rows
        if len(rows) >= 2:
            first_row = rows[0]
            second_row = rows[1] if len(rows) > 1 else []
            # First row looks like header if mostly non-numeric and short text
            first_numeric = sum(_looks_numeric(c) for c in first_row)
            second_numeric = sum(_looks_numeric(c) for c in second_row)
            if (first_numeric == 0 and second_numeric > 0
                    and all(len(c) < 50 for c in first_row)):
                header_row = first_row
                data_rows = rows[1:]

        col_count = max(len(r) for r in rows) if rows else 0
        tables.append({
            "rows": rows,
            "row_count": len(rows),
            "col_count": col_count,
            "header_row": header_row,
            "data_rows": data_rows,
        })

    return tables


def _looks_numeric(value: str) -> bool:
    """Heuristic: does this cell contain a number?"""
    if not value:
        return False
    # Strip currency symbols, commas, percent signs
    cleaned = re.sub(r"[₹$€£%,\s]", "", value)
    # Allow leading minus and decimal point
    return bool(re.match(r"^-?\d+(\.\d+)?$", cleaned))


def parse_amount(value: str) -> float | None:
    """Parse a financial amount cell. Returns float or None for unparseable."""
    if not value or value.strip() in {"-", "—", "–", ""}:
        return None
    cleaned = value.replace(",", "").replace("\u00a0", "").strip()
    cleaned = cleaned.replace("₹", "").replace("$", "")
    try:
        return float(cleaned)
    except ValueError:
        return None


def find_table_with_headers(
    html: str,
    required_keywords: list[str],
    case_sensitive: bool = False,
) -> dict[str, Any] | None:
    """Find the first table whose header row contains all required keywords.

    Useful for: "find me the bank-credit table" (keywords: tran date, particulars,
    credit amount) or "find me the invoice-allocation table" (keywords: invoice,
    amount).

    Returns the table dict or None if no match.
    """
    tables = extract_html_tables(html)
    for tbl in tables:
        if not tbl["header_row"]:
            continue
        header_text = " ".join(tbl["header_row"])
        if not case_sensitive:
            header_text = header_text.lower()
            required = [k.lower() for k in required_keywords]
        else:
            required = required_keywords
        if all(k in header_text for k in required):
            return tbl
    return None
