# html_tools.py
"""
HTML extraction utilities for remittance email bodies.

Real Adani emails are HTML with embedded tables. The body is generated by
Outlook/Word and is typical Microsoft HTML — heavy with style attributes,
nested spans, soft hyphens, and non-breaking spaces.

These tools handle the parsing so the agent can reason about table content
instead of HTML structure.
"""

import re
from typing import Any

from bs4 import BeautifulSoup, Tag


def extract_plain_text(html: str) -> str:
    """Strip HTML to plain text. Good for previewing or for LLM context."""
    soup = BeautifulSoup(html, "lxml")
    # Remove style and script
    for el in soup(["style", "script"]):
        el.decompose()
    text = soup.get_text(separator=" ", strip=True)
    # Normalize whitespace (Outlook HTML has lots of repeated spaces and nbsp)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def _normalize_cell(cell_text: str) -> str:
    """Clean a single cell value: strip whitespace, collapse spaces, handle dashes."""
    s = cell_text.strip()
    s = re.sub(r"\s+", " ", s)
    # Outlook puts non-breaking spaces and soft hyphens everywhere
    s = s.replace("\u00a0", " ").replace("\u00ad", "")
    # Dash-only cells often mean "0" or "—" in financial tables
    if s in {"-", "—", "–"}:
        return ""
    return s.strip()


def extract_html_tables(html: str) -> list[dict[str, Any]]:
    """Extract all <table> elements from HTML, return as list of structured dicts.

    Each table is returned as:
        {
            "rows": [[cell1, cell2, ...], [cell1, cell2, ...], ...],
            "row_count": int,
            "col_count": int,
            "header_row": [...] | None,   # heuristic: first row if it looks like headers
            "data_rows": [[...], ...],     # rows after the header
        }

    Header detection is heuristic: if the first row's cells contain mostly
    non-numeric content AND the second row's cells contain numeric content,
    treat the first row as headers. Otherwise no header is identified and
    all rows are data.
    """
    soup = BeautifulSoup(html, "lxml")
    tables = []
    for tbl in soup.find_all("table"):
        rows = []
        for tr in tbl.find_all("tr"):
            cells = [_normalize_cell(td.get_text(separator=" ", strip=True))
                     for td in tr.find_all(["td", "th"])]
            if cells:  # skip rows with no cells (formatting artifacts)
                rows.append(cells)

        if not rows:
            continue

        # Heuristic header detection
        header_row = None
        data_rows = rows
        if len(rows) >= 2:
            first_row = rows[0]
            second_row = rows[1] if len(rows) > 1 else []
            # First row looks like header if mostly non-numeric and short text
            first_numeric = sum(_looks_numeric(c) for c in first_row)
            second_numeric = sum(_looks_numeric(c) for c in second_row)
            if (first_numeric == 0 and second_numeric > 0
                    and all(len(c) < 50 for c in first_row)):
                header_row = first_row
                data_rows = rows[1:]

        col_count = max(len(r) for r in rows) if rows else 0
        tables.append({
            "rows": rows,
            "row_count": len(rows),
            "col_count": col_count,
            "header_row": header_row,
            "data_rows": data_rows,
        })

    return tables


def _looks_numeric(value: str) -> bool:
    """Heuristic: does this cell contain a number?"""
    if not value:
        return False
    # Strip currency symbols, commas, percent signs
    cleaned = re.sub(r"[₹$€£%,\s]", "", value)
    # Allow leading minus and decimal point
    return bool(re.match(r"^-?\d+(\.\d+)?$", cleaned))


def parse_amount(value: str) -> float | None:
    """Parse a financial amount cell. Returns float or None for unparseable."""
    if not value or value.strip() in {"-", "—", "–", ""}:
        return None
    cleaned = value.replace(",", "").replace("\u00a0", "").strip()
    cleaned = cleaned.replace("₹", "").replace("$", "")
    try:
        return float(cleaned)
    except ValueError:
        return None


def find_table_with_headers(
    html: str,
    required_keywords: list[str],
    case_sensitive: bool = False,
) -> dict[str, Any] | None:
    """Find the first table whose header row contains all required keywords.

    Useful for: "find me the bank-credit table" (keywords: tran date, particulars,
    credit amount) or "find me the invoice-allocation table" (keywords: invoice,
    amount).

    Returns the table dict or None if no match.
    """
    tables = extract_html_tables(html)
    for tbl in tables:
        if not tbl["header_row"]:
            continue
        header_text = " ".join(tbl["header_row"])
        if not case_sensitive:
            header_text = header_text.lower()
            required = [k.lower() for k in required_keywords]
        else:
            required = required_keywords
        if all(k in header_text for k in required):
            return tbl
    return None


# ============================================================
# Triage-oriented table finders
# ============================================================
#
# Each finder looks for a specific kind of table by checking header keywords.
# Returns the FIRST matching table found in body order (skipping later
# duplicates that come from quoted forward chains).


def find_bank_credit_table(html: str) -> dict | None:
    """Find the bank-credit table.

    Two formats observed in real samples:
    - NEFT format: 'Tran Date / Particulars / Credit Amount'
    - Cheque/IFT format: 'Co Code / Collection Date / Chq No & Bank GL /
      Particulars / Collection Amt'

    Returns the first matching table or None.
    """
    # Try NEFT format first (most common — 9 of 10 samples)
    table = find_table_with_headers(html, ["tran date", "credit amount"])
    if table:
        return table

    # Try cheque/IFT format (1 of 10 samples)
    table = find_table_with_headers(html, ["collection date", "collection amt"])
    if table:
        return table

    # Fallback: any table with 'particulars' and an amount column
    # (catches edge cases where headers are slightly different)
    table = find_table_with_headers(html, ["particulars"])
    if table:
        # Verify it has at least 3 columns and looks like a credit table
        if table["col_count"] >= 3:
            return table

    return None


def find_allocation_table(html: str) -> dict | None:
    """Find the invoice-allocation table.

    Real samples use varying header names for the same logical columns:
    - Customer ID: Customer / Cust.No / Co Code / Customer Code / Code / Company Code
    - Customer name: Customer name / Cust.Name / Company Name
    - Invoice column: Reference / Invoice No / Invoice No.
    - Amount columns: Amount / Amt / Invoice Amt / Invoice Amount / Net Amount

    Strategy: an allocation table has at least three of these signals:
    1. A customer-identifier column
    2. An invoice-reference column
    3. An amount column

    Excludes aging reports (which have bucket headers like '00 - 0030').

    Returns the first matching table or None.
    """
    tables = extract_html_tables(html)

    customer_keywords = {
        "customer", "cust.no", "cust no", "co code", "customer code",
        "company code", "company name", "cust.name",
    }
    invoice_keywords = {
        "reference", "invoice no", "invoice no.", "invoice number",
    }
    amount_keywords = {
        "amount", "amt", "invoice amt", "invoice amount", "net amount", "net amt",
    }
    aging_indicators = {
        "00 - 0030", "31 - 0090", "91 - 0180", "181 - 0365", "366 - 1095",
        "00-0030", "31-0090", "91-0180",
    }

    for tbl in tables:
        if not tbl["header_row"]:
            continue

        header_lower = [h.lower() for h in tbl["header_row"]]
        header_text = " ".join(header_lower)

        # Skip aging reports
        if any(indicator in header_text for indicator in aging_indicators):
            continue

        # Need to be at least 4 columns (customer, name, invoice, amount minimum)
        if tbl["col_count"] < 4:
            continue

        has_customer = any(k in header_text for k in customer_keywords)
        has_invoice = any(k in header_text for k in invoice_keywords)
        has_amount = any(k in header_text for k in amount_keywords)

        if has_customer and has_invoice and has_amount:
            return tbl

    return None


def find_customer_only_table(html: str) -> dict | None:
    """Find a 2-column 'Customer / Customer name' table.

    This is the partial_booking signature — customer is identified but no
    invoice allocation is provided. Used for cases like 'Please Book on FIFO
    Basis' where Mahek leaves the invoice allocation to the collections team.

    Returns the table or None.
    """
    tables = extract_html_tables(html)

    for tbl in tables:
        if not tbl["header_row"]:
            continue
        if tbl["col_count"] != 2:
            continue

        header_lower = [h.lower() for h in tbl["header_row"]]

        # Must look like (customer-id, customer-name)
        first_col = header_lower[0]
        second_col = header_lower[1]

        first_is_customer_id = any(
            k in first_col
            for k in ("customer", "cust.no", "cust no", "code")
        )
        second_is_customer_name = any(
            k in second_col
            for k in ("customer name", "cust.name", "company name", "name")
        )

        if first_is_customer_id and second_is_customer_name:
            return tbl

    return None


def find_account_reference(text: str) -> str | None:
    """Find an 'On A/C - <number>' reference in plain email text.

    Used to detect on_account_only emails: 'On A/C – 4000000321' or
    'On A/C - 13139'. The dash may be hyphen, en-dash, or em-dash.

    Returns the account reference number as a string, or None.
    """
    import re

    # Pattern: 'On A/C' followed by - or – or — and a digit sequence
    pattern = re.compile(
        r"on\s+a\s*/\s*c\s*[\-\u2013\u2014]\s*(\d+)",
        re.IGNORECASE,
    )
    match = pattern.search(text)
    if match:
        return match.group(1)
    return None


def find_payment_intent(text: str) -> tuple[str | None, str | None]:
    """Detect special payment instructions in email body text.
    
    Returns (intent_value, raw_remark) where intent_value is one of:
        'advance', 'security_deposit', 'on_account', 'fifo_instruction',
        'other_special', or None if no remark detected.
    
    Returns the raw matched text as the second element for audit.
    """
    import re

    # Order matters: more specific patterns first so they win
    patterns = [
        # Security deposit (specific — check before "advance" because
        # 'security deposit advance' is still a deposit)
        ("security_deposit",
         re.compile(r"\bsecurity\s+deposit\b", re.IGNORECASE)),

        # Advance payment (explicit)
        ("advance",
         re.compile(r"\badvance\s+payment\b", re.IGNORECASE)),

        # Advance (single word)
        ("advance",
         re.compile(r"(?:^|\W)(advance)(?:\W|$)", re.IGNORECASE)),

        # On account / On A/C (case-insensitive, allowing for variants)
        ("on_account",
         re.compile(r"\bon\s+a\s*/\s*c\b", re.IGNORECASE)),

        ("on_account",
         re.compile(r"\bon\s+account\b", re.IGNORECASE)),

        # FIFO instruction
        ("fifo_instruction",
         re.compile(r"(?:please\s+)?book\s+on\s+fifo|fifo\s+basis", re.IGNORECASE)),
    ]

    for intent, pattern in patterns:
        match = pattern.search(text)
        if match:
            # Capture the surrounding context (~50 chars on each side) for audit
            start = max(0, match.start() - 30)
            end = min(len(text), match.end() + 30)
            raw_remark = text[start:end].strip()
            return intent, raw_remark

    return None, None